# Generated by Django 2.0.5 on 2018-07-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de iglesia')),
                ('direction', models.CharField(max_length=500, verbose_name='Dirección')),
                ('image', models.ImageField(upload_to='church', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name_plural': 'Iglesias',
                'verbose_name': 'Iglesia',
                'ordering': ['created'],
            },
        ),
    ]
