# Generated by Django 2.0.5 on 2018-07-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='content',
            field=models.TextField(default=0, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
