# Generated by Django 2.0.5 on 2018-07-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20180712_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='church',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Region', verbose_name='Región'),
        ),
    ]
