# Generated by Django 2.0.5 on 2018-07-08 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20180708_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='category',
            field=models.CharField(blank=True, choices=[('Diezmos', 'Diezmos'), ('Ofrendas', 'Ofrendas')], default='O', max_length=1, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='name_church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='Nombre de iglesia'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='position',
            field=models.CharField(blank=True, choices=[('P', 'Presidente'), ('V', 'Vice_presidente'), ('S', 'Secretario'), ('T', 'Tesorero'), ('M', 'Miembro')], default='M', max_length=12, verbose_name='Cargo'),
        ),
    ]
