# Generated by Django 2.0.5 on 2018-07-12 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_auto_20180712_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='region',
        ),
        migrations.AlterField(
            model_name='finance',
            name='name_church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='Nombre de iglesia'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
