# Generated by Django 2.0.5 on 2018-07-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20180712_0205'),
        ('finance', '0034_auto_20180712_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='church.District', verbose_name='Dirstrito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finance',
            name='name_church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='Nombre de iglesia'),
        ),
    ]
