# Generated by Django 2.0.5 on 2018-07-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_auto_20180712_1532'),
        ('finance', '0037_auto_20180712_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='church.Region', verbose_name='Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finance',
            name='name_church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='Nombre de iglesia'),
        ),
    ]
