# Generated by Django 2.0.5 on 2018-07-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_auto_20180712_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='code',
            field=models.CharField(default=0, max_length=6, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finance',
            name='name_church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='Nombre de iglesia'),
        ),
    ]
